# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\"n\n\x10\x46raudInitRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x02 \x01(\t\x12\x14\n\x0corder_amount\x18\x03 \x01(\x02\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x05 \x01(\t\"$\n\x11\x46raudInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\";\n\x11\x46raudCheckRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x14\n\x0cvector_clock\x18\x02 \x03(\x05\"M\n\x12\x46raudCheckResponse\x12\x10\n\x08is_fraud\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0cvector_clock\x18\x03 \x03(\x05\x32\xa0\x02\n\x15\x46raudDetectionService\x12R\n\tInitOrder\x12!.fraud_detection.FraudInitRequest\x1a\".fraud_detection.FraudInitResponse\x12X\n\rCheckUserData\x12\".fraud_detection.FraudCheckRequest\x1a#.fraud_detection.FraudCheckResponse\x12Y\n\x0e\x43heckCardFraud\x12\".fraud_detection.FraudCheckRequest\x1a#.fraud_detection.FraudCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAUDINITREQUEST']._serialized_start=42
  _globals['_FRAUDINITREQUEST']._serialized_end=152
  _globals['_FRAUDINITRESPONSE']._serialized_start=154
  _globals['_FRAUDINITRESPONSE']._serialized_end=190
  _globals['_FRAUDCHECKREQUEST']._serialized_start=192
  _globals['_FRAUDCHECKREQUEST']._serialized_end=251
  _globals['_FRAUDCHECKRESPONSE']._serialized_start=253
  _globals['_FRAUDCHECKRESPONSE']._serialized_end=330
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=333
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=621
# @@protoc_insertion_point(module_scope)
