# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_queue.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11order_queue.proto\x12\x0border_queue\"+\n\tOrderItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"i\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12%\n\x05items\x18\x02 \x03(\x0b\x32\x16.order_queue.OrderItem\x12\x11\n\tuser_name\x18\x03 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x04 \x01(\x02\"3\n\x0e\x45nqueueRequest\x12!\n\x05order\x18\x01 \x01(\x0b\x32\x12.order_queue.Order\"4\n\x0f\x45nqueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08order_id\x18\x02 \x01(\t\"\x10\n\x0e\x44\x65queueRequest\"E\n\x0f\x44\x65queueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12!\n\x05order\x18\x02 \x01(\x0b\x32\x12.order_queue.Order2\x9f\x01\n\x11OrderQueueService\x12\x44\n\x07\x45nqueue\x12\x1b.order_queue.EnqueueRequest\x1a\x1c.order_queue.EnqueueResponse\x12\x44\n\x07\x44\x65queue\x12\x1b.order_queue.DequeueRequest\x1a\x1c.order_queue.DequeueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERITEM']._serialized_start=34
  _globals['_ORDERITEM']._serialized_end=77
  _globals['_ORDER']._serialized_start=79
  _globals['_ORDER']._serialized_end=184
  _globals['_ENQUEUEREQUEST']._serialized_start=186
  _globals['_ENQUEUEREQUEST']._serialized_end=237
  _globals['_ENQUEUERESPONSE']._serialized_start=239
  _globals['_ENQUEUERESPONSE']._serialized_end=291
  _globals['_DEQUEUEREQUEST']._serialized_start=293
  _globals['_DEQUEUEREQUEST']._serialized_end=309
  _globals['_DEQUEUERESPONSE']._serialized_start=311
  _globals['_DEQUEUERESPONSE']._serialized_end=380
  _globals['_ORDERQUEUESERVICE']._serialized_start=383
  _globals['_ORDERQUEUESERVICE']._serialized_end=542
# @@protoc_insertion_point(module_scope)
