# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_verification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'transaction_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x0btransaction\"\xd1\x01\n\x1eTransactionVerificationRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x03 \x01(\t\x12\x12\n\ncreditCard\x18\x04 \x01(\t\x12\x12\n\nitemsCount\x18\x05 \x01(\x05\x12\x0b\n\x03\x63vv\x18\x06 \x01(\t\x12\x0e\n\x06street\x18\x07 \x01(\t\x12\x0c\n\x04\x63ity\x18\x08 \x01(\t\x12\x0b\n\x03zip\x18\t \x01(\t\x12\x0f\n\x07\x63ountry\x18\n \x01(\t\x12\r\n\x05state\x18\x0b \x01(\t\"7\n\rVerifyRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x14\n\x0cvector_clock\x18\x02 \x03(\x05\"I\n\x0eVerifyResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0cvector_clock\x18\x03 \x03(\x05\"$\n\x11InitOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xda\x02\n\x1eTransactionVerificationService\x12X\n\tInitOrder\x12+.transaction.TransactionVerificationRequest\x1a\x1e.transaction.InitOrderResponse\x12\x46\n\x0bVerifyItems\x12\x1a.transaction.VerifyRequest\x1a\x1b.transaction.VerifyResponse\x12I\n\x0eVerifyUserData\x12\x1a.transaction.VerifyRequest\x1a\x1b.transaction.VerifyResponse\x12K\n\x10VerifyCreditCard\x12\x1a.transaction.VerifyRequest\x1a\x1b.transaction.VerifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_start=48
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_end=257
  _globals['_VERIFYREQUEST']._serialized_start=259
  _globals['_VERIFYREQUEST']._serialized_end=314
  _globals['_VERIFYRESPONSE']._serialized_start=316
  _globals['_VERIFYRESPONSE']._serialized_end=389
  _globals['_INITORDERRESPONSE']._serialized_start=391
  _globals['_INITORDERRESPONSE']._serialized_end=427
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=430
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=776
# @@protoc_insertion_point(module_scope)
